[tool.poetry]
name = "agentok-api"
version = "0.1.1"
description = "Agentok APIs"
authors = ["Dustland <agentok@dustland.ai>"]
readme = "README.md"
package-mode = false

[tool.virtualenvs]
in-project = true
create = true
prefer-active-python = true

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
diskcache = "5.6.3"
fastapi = "0.115.5"
gotrue = "2.11.0"
Jinja2 = "3.1.6"
Pillow = "10.4"
pydantic = ">=2.10.4"
python-dotenv = "1.0.1"
regex = "2024.11.6"
requests = "2.32.3"
starlette = "0.41.3"
termcolor = "2.3.0"
uvicorn = "^0.32.0"
supabase = "^2.13.0"
tavily-python = "^0.5.0"
cohere = "^5.8.0"
python-magic = "^0.4.27"
autogen = { version = "0.7.3", extras = ["browser-use"] }
httpx = {version = ">=0.26,<0.28", extras = ["socks", "http2"]}
socksio = "^1.0.0"
sentence-transformers = "^3.3.1"
playwright = "^1.42.0"
nest-asyncio = "^1.6.0"
agentops = "^0.3.26"

[tool.poetry.group.dev.dependencies]
black = "^24.3"
isort = "^5.9.3"
alembic = "^1.7.4"
pipreqs = "^0.5.0"

[tool.black]
line-length = 88
target-version = ['py38']

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
