name: Discord Release Notification

on:
  release:
    types: [published]

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Send Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_ANN }}
          RELEASE_TAG: ${{ github.event.release.tag_name }}
          RELEASE_NAME: ${{ github.event.release.name }}
          RELEASE_BODY: ${{ github.event.release.body }}
          RELEASE_URL: ${{ github.event.release.html_url }}
        run: |
          curl -H "Content-Type: application/json" -X POST -d @- $DISCORD_WEBHOOK <<EOF
          {
            "embeds": [{
              "title": "New Release: $RELEASE_TAG",
              "description": "$RELEASE_NAME\n\n$RELEASE_BODY",
              "url": "$RELEASE_URL",
              "color": 3066993
            }]
          }
          EOF
