name: Discord Notification On Release

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Discord (announcements)
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_ANN }}
        run: |
          curl -H "Content-Type: application/json" -X POST -d "{\"username\": \"GitHub Notification\", \"avatar_url\": \"https://octodex.github.com/images/original.png\", \"embeds\": [{\"title\": \"New Release Published\", \"description\": \"${{ github.event.release.name }} has been released.\", \"url\": \"${{ github.event.release.html_url }}\", \"color\": 5814783}]}" $DISCORD_WEBHOOK
